export const PUBLIC_ALPHA_POLICY_VERSION = "public-alpha-2026-07-23";
export const MAXIMUM_D1_RECOVERY_WINDOW_DAYS = 30;
export const ACCOUNT_DELETION_CONFIRMATION = "DELETE";
export const ACCOUNT_RESTART_CONFIRMATION = "START AGAIN";
